# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://yoursite.com
title: Discovery Studio
email: discovery@berger.wtf
author: jpb
description: > # "Write an awesome description for your new site here.
  Discovery Studio helps you build digital product with a world-class background in agile software deveolpment and product design.

copyright: 'Copyright &copy; 2016 Discovery Studio. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/disc0verylabs
  - title: github
    url: https://github.com/jonathanpberger
  - title: linkedin
    url:

# ----------------------- #
#   Heroku Settings (from https://www.jamesward.com/2014/09/24/jekyll-on-heroku)
# ----------------------- #

gems: ['kramdown']
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile']
